---
- name: "Install requirements"
  ansible.builtin.package:
    name: ['unzip', 'imagemagick']
    state: present

- name: Check if Omeka Classic directories already exists
  ansible.builtin.stat:
    path: "{{ omeka_classic_content_dest }}"
  register: omeka_classic_installed

- name: Backup Omeka Classic directories (update only)
  ansible.builtin.command:
    cmd: mv {{ omeka_classic_content_dest }} {{ omeka_classic_backup_directory }}
  when: omeka_classic_installed.stat.exists and omeka_classic_force_update

- name: Download and extract Omeka Classic
  ansible.builtin.unarchive:
    src: "{{ omeka_classic_download_url }}"
    remote_src: true
    dest: "{{ omeka_classic_unarchive_dir }}"
    owner: "{{ omeka_classic_web_owner }}"
    group: "{{ omeka_classic_web_group }}"
    validate_certs: false
  when: not omeka_classic_installed.stat.exists or omeka_classic_force_update

- name: Check if Omeka Classic extract directory still exist (idempotence)
  ansible.builtin.stat:
    path: "{{ omeka_classic_unarchive_content_dest }}"
  register: omeka_classic_is_unarchived

- name: Rename Extract folder to keep links up
  ansible.builtin.command:
    cmd: mv {{ omeka_classic_unarchive_content_dest }} {{ omeka_classic_content_dest }}
  when: omeka_classic_is_unarchived.stat.exists

- name: Set permisions to files directory
  ansible.builtin.file:
    path: "{{ omeka_classic_content_dest }}/files"
    owner: "{{ omeka_classic_web_owner }}"
    group: "{{ omeka_classic_web_group }}"
    mode: "0755"
  when: not omeka_classic_installed.stat.exists or omeka_classic_force_update

- name: Restore your configurations files (Update Only)
  ansible.builtin.copy:
    src: "{{ omeka_classic_backup_directory }}/{{ item }}"
    dest: "{{ omeka_classic_content_dest }}/"
    owner: "{{ omeka_classic_web_owner }}"
    group: "{{ omeka_classic_web_group }}"
    force: true
    remote_src: true
  with_items:
    - "files"
    - "plugins"
    - "themes"
  when: omeka_classic_installed.stat.exists and omeka_classic_force_update

- name: Copy db.ini
  ansible.builtin.template:
    src: db.ini.j2
    owner: "{{ omeka_classic_web_owner }}"
    group: "{{ omeka_classic_web_group }}"
    dest: "{{ omeka_classic_content_dest }}/db.ini"
    mode: "0644"
  notify: Change Web directory owner
