---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: supertarto.apache
    - role: supertarto.mariadb
    - role: supertarto.php
    - role: supertarto.omeka_classic

  vars:
    php_packages:
      - php7.3
      - php7.3-mysql
      - php7.3-exif

    apache_create_vhosts: true
    apache_vhosts_filename: "omeka.conf"
    apache_vhost_config:
      - listen_ip: "*"
        listen_port: 80
        server_name: host1
        documentroot: "{{ omeka_classic_content_dest }}"
        serveradmin: admin@localhost
        custom_param: |
          ErrorLog ${APACHE_LOG_DIR}/error.log
          CustomLog ${APACHE_LOG_DIR}/access.log combined
          LogLevel warn
        directory:
          - path: "{{ omeka_classic_content_dest }}"
            config: |
              AllowOverride All
              Order deny,allow
              allow from all

        mariadb_use_dump_script: false
        mariadb_databases:
          - name: "{{ omeka_classic_db_name }}"

        mariadb_users:
          - name: "{{ omeka_classic_db_user }}"
            host: "{{ omeka_classic_db_host }}"
            password: "{{ omeka_classic_db_password }}"
            priv: "{{ omeka_classic_db_name }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER,CREATE TEMPORARY TABLES,LOCK TABLES"

    omeka_classic_release_version: "2.7.1"
    omeka_classic_db_user: omeka
    omeka_classic_db_password: omekapass
    omeka_classic_db_name: omekadb
    omeka_classic_db_host: localhost
